---
abstract: 'check xt tests before release'
author:
  - 'David Golden <dagolden@cpan.org>'
build_requires:
  Capture::Tiny: 0
  Dist::Zilla::App::Tester: 0
  Dist::Zilla::Tester: 0
  File::Find: 0
  Params::Util: 0
  Sub::Exporter: 0
  Test::More: 0.88
  Try::Tiny: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
generated_by: 'Dist::Zilla version 2.100960'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-CheckExtraTests
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
provides:
  Dist::Zilla::App::Command::xtest:
    file: lib/Dist/Zilla/App/Command/xtest.pm
    version: 0.003
  Dist::Zilla::Plugin::CheckExtraTests:
    file: lib/Dist/Zilla/Plugin/CheckExtraTests.pm
    version: 0.003
recommends: {}
requires:
  App::Prove: 3.00
  Dist::Zilla: 2.100950
  Dist::Zilla::App: 0
  Dist::Zilla::Role::BeforeRelease: 0
  File::Temp: 0
  File::pushd: 0
  Moose: 0.99
  Moose::Autobox: 0
  Path::Class: 0
  namespace::autoclean: 0.09
resources:
  repository: http://github.com/dagolden/dist-zilla-plugin-checkextratests
version: 0.003
