---
abstract: 'check xt tests before release'
author:
  - 'David Golden <dagolden@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100711'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-CheckExtraTests
no_index:
  directory:
    - t
    - xt
    - examples
provides:
  Dist::Zilla::App::Command::xtest:
    file: lib/Dist/Zilla/App/Command/xtest.pm
    version: 0.002
  Dist::Zilla::Plugin::CheckExtraTests:
    file: lib/Dist/Zilla/Plugin/CheckExtraTests.pm
    version: 0.002
requires:
  App::Prove: 3.00
  Capture::Tiny: 0
  Dist::Zilla: 1.093250
  Dist::Zilla::App: 0
  Dist::Zilla::Role::BeforeRelease: 0
  File::Find: 0
  File::Temp: 0
  File::chdir: 0.1002
  Moose: 0.99
  Moose::Autobox: 0
  Path::Class: 0
  Test::Exception: 0
  Test::More: 0
  namespace::autoclean: 0.09
resources:
  repository: http://github.com/dagolden/dist-zilla-plugin-checkextratests
version: 0.002
