---
abstract: 'check xt tests before release'
author:
  - 'David Golden <dagolden@cpan.org>'
  - 'Jesse Luehrs <doy@cpan.org>'
build_requires:
  Capture::Tiny: 0
  Dist::Zilla::App::Tester: 0
  Dist::Zilla::Tester: 0
  File::Find: 0
  Params::Util: 0
  Sub::Exporter: 0
  Test::More: 0.88
  Test::Requires: 0
  Try::Tiny: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300016, CPAN::Meta::Converter version 2.120921'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-CheckExtraTests
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  Dist::Zilla::App::Command::xtest:
    file: lib/Dist/Zilla/App/Command/xtest.pm
    version: 0.007
  Dist::Zilla::Plugin::CheckExtraTests:
    file: lib/Dist/Zilla/Plugin/CheckExtraTests.pm
    version: 0.007
  Dist::Zilla::Plugin::RunExtraTests:
    file: lib/Dist/Zilla/Plugin/RunExtraTests.pm
    version: 0.007
requires:
  App::Prove: 3.00
  Dist::Zilla: 2.100950
  Dist::Zilla::App: 0
  Dist::Zilla::Role::BeforeRelease: 0
  Dist::Zilla::Role::TestRunner: 0
  File::Temp: 0
  File::pushd: 0
  Moose: 0.99
  Moose::Autobox: 0
  Path::Class: 0
  Path::Class::Rule: 0
  namespace::autoclean: 0.09
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Dist-Zilla-Plugin-CheckExtraTests
  homepage: https://github.com/dagolden/dist-zilla-plugin-checkextratests
  repository: https://github.com/dagolden/dist-zilla-plugin-checkextratests.git
version: 0.007
